### ISSUE TITLE
Invalid for zotero 6.0

### ISSUE THREAD

**Issue by dualer** [odkr/pandoc-zotxt.lua#8]
Zotero beta has updated to v6.0,  and this filter may be invalid for it.

**Comment by odkr** [comment]
Could you elaborate? Does it fail to do something—or are you just worried ;-)? pandoc-zotxt.lua uses the zotxt add-on to fetch data from Zotero, and to the best of my knowledge, Zotero v6 will not introduce breaking changes to the add-on API, so zotxt, and by extension, pandoc-zotxt.lua should continue to work just fine. I also just tested it with the latest Zotero beta, and don't see any problems. If Zotero v6 introduces breaking changes after all, that's why pandoc-zotxt.lua supports the Zotero Web API, too.

**Comment by dualer** [comment]
The problem should be caused by the addon `zotxt`, more information see https://github.com/egh/zotxt/issues/31.

**Comment by odkr** [comment]
Thanks for the heads-up! Weirdly, the pandoc-zotxt.lua test suite passes for Zotero v6.0-beta.1+c6d03753f. So, either this has been fixed already, and quite quickly, or it's Linux-specific, or pandoc-zotxt.lua is just not using the functionality that triggers the bug. 🤷 I'll keep an eye on this. If you are experiencing problems, you can try to switch to the Web API. You'd need to get an API key from Zotero and set it using the `zotero-api-key` metadata field. And you'll likely want to change the BetterBibTeX citation key format to "[auth:lower][year][shorttitle3_3]". The manual has more details.

**Comment by njbart** [comment]
Works as expected for me (on Zotero 6.0-beta.1+c6d03753f). The zotxt add-on did not work initially after the Zotero update to 6.0, but after a zotxt commit [“Mark as compatible with zotero 6”](https://github.com/egh/zotxt/commit/63f943bc5e2da13dcc1bba796482e44ca17b74fd), the zotxt add-on auto-updated itself in my Zotero installation. After that, everything was back to normal.

**Comment by odkr** [comment]
Okay, so this *has* been resolved quickly. Good to know! Thanks a lot for filling in the details!
